// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
)

type Info struct {
	Address       sql.NullString `json:"address"`
	PhoneNumber   sql.NullString `json:"phone_number"`
	ContactPerson sql.NullString `json:"contact_person"`
	NodeID        sql.NullInt32  `json:"node_id"`
}

type Node struct {
	ID       int32         `json:"id"`
	Name     string        `json:"name"`
	ParentID sql.NullInt32 `json:"parent_id"`
}
